; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 2MB
# Anadir dependencias desde el registro de componentes de Espressif
lib_deps =
    lvgl/lvgl @ ^8.3.11

build_flags =
    -D LV_CONF_SKIP=1
    -D LV_LVGL_H_INCLUDE_SIMPLE=1